#ifndef DIS_TABLE_H
#define DIS_TABLE_H

//#include "SCInstr.h"
#include "instruction.h"


enum HAVE_AUXILIARY_CODE{
    AUXILIARY_80, AUXILIARY_81, AUXILIARY_82, AUXILIARY_83,
    AUXILIARY_8f, AUXILIARY_c0, AUXILIARY_c1, AUXILIARY_c6,
    AUXILIARY_c7, AUXILIARY_d0, AUXILIARY_d1, AUXILIARY_d2,
    AUXILIARY_d3, AUXILIARY_d8, AUXILIARY_d9, AUXILIARY_da,
    AUXILIARY_db, AUXILIARY_dc, AUXILIARY_dd, AUXILIARY_de,
    AUXILIARY_df, AUXILIARY_f6, AUXILIARY_f7, AUXILIARY_fe,
    AUXILIARY_ff, AUXILIARY_0f00, AUXILIARY_0f01, AUXILIARY_0f18,
    AUXILIARY_0fae, AUXILIARY_0fba
};

enum FLOAT_POINT_INSTRUCTION{
    FLOAT_d8, FLOAT_d9, FLOAT_da, FLOAT_db,
    FLOAT_dc, FLOAT_dd, FLOAT_de, FLOAT_df
};

enum SPECIAL_INSTRUCTION{
    SPECIAL_d9e0, SPECIAL_d9e1, SPECIAL_d9e4, SPECIAL_d9e5,
    SPECIAL_d9e8, SPECIAL_d9e9, SPECIAL_d9ea, SPECIAL_d9eb,
    SPECIAL_d9ec, SPECIAL_d9ed, SPECIAL_d9ee, SPECIAL_d9f0,
    SPECIAL_d9f1, SPECIAL_d9f2, SPECIAL_d9f3, SPECIAL_d9f4,
    SPECIAL_d9f5, SPECIAL_d9f6, SPECIAL_d9f7, SPECIAL_d9f8,
    SPECIAL_d9f9, SPECIAL_d9fa, SPECIAL_d9fb, SPECIAL_d9fc,
    SPECIAL_d9fd, SPECIAL_d9fe, SPECIAL_d9ff, SPECIAL_dbe0,
    SPECIAL_dbe1, SPECIAL_dbe2, SPECIAL_dbe3, SPECIAL_dbe4,
    SPECIAL_60, SPECIAL_61, SPECIAL_9c, SPECIAL_9d,
    SPECIAL_90_1, SPECIAL_90_2, SPECIAL_98, SPECIAL_99,
    SPECIAL_cf, SPECIAL_d4, SPECIAL_d5, SPECIAL_e0,
    SPECIAL_e1, SPECIAL_e2, SPECIAL_e3, SPECIAL_0f10_1,
    SPECIAL_0f10_2, SPECIAL_0f10_3, SPECIAL_0f11_1, SPECIAL_0f11_2,
    SPECIAL_0f11_3, SPECIAL_0f12_1, SPECIAL_0f12_2, SPECIAL_0f12_3,
    SPECIAL_0f12_4, SPECIAL_0f13, SPECIAL_0f14, SPECIAL_0f15,
    SPECIAL_0f16_1, SPECIAL_0f16_2, SPECIAL_0f16_3, SPECIAL_0f17,
    SPECIAL_0f28, SPECIAL_0f29, SPECIAL_0f2a_1, SPECIAL_0f2a_2,
    SPECIAL_0f2a_3, SPECIAL_0f2b, SPECIAL_0fb8, SPECIAL_PREFIX
};

extern INSTRUCTION onlyPrefix;
extern INSTRUCTION getOneByteOpcode[];
extern INSTRUCTION getTwoByteOpcode[];
extern INSTRUCTION getOneByteWithAuxiliaryOpcode[][8];
extern INSTRUCTION floatInstruction_2[][8];
extern INSTRUCTION specialInstruction[];

#endif
